### ISSUE TITLE
Studio URL: change studio url path to a more suitable name

### ISSUE THREAD

**Issue by ashklianko** [enonic/app-contentstudio#4031] opened 2021-12-23 08:41 UTC
1. Current url when Studio app is opened will be `/browse`, meanwhile Settings and Archive have correpsonding and self-describing names. `/studio` will suite better

**Comment by alansemenov** [comment] 2021-12-23 13:51
Duplicate of https://github.com/enonic/app-contentstudio/issues/4032

**Closed as completed by alansemenov** 2021-12-23 13:51 UTC
Labels: Tech Debt
