### ISSUE TITLE
Incorrect notification message when a project has been deleted in another browser window

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1767] opened 2020-04-30 08:56 UTC
1. Create an user and create a project (select the user in Custom read permissions)
2. Login with the user and open Settings grid.
3. Switch to browser where SU is logged in and delete the project.
4. switch to browser where new user is  logged in 
**BUG** :  Incorrect notification message appears in Browse Panel: 

![image](https://user-images.githubusercontent.com/3728712/80691877-81e49900-8ad9-11ea-9bd7-f9cf4565fd4d.png)

**Expected: Project [pr1] is deleted**

**Comment by ashklianko** [comment] 2020-05-10 09:40
Unable to reproduce, @sgauruseu need your input

**Comment by alansemenov** [comment] 2020-05-11 07:05
Was most likely fixed by https://github.com/enonic/app-contentstudio/issues/1761

**Comment by sgauruseu** [comment] 2020-05-11 11:54
Yes , incorrect notification does not appear , but expected message "Project is deleted "  is not displayed either

**Comment by sgauruseu** [comment] 2020-05-11 11:56
Messages do not appear at all when deleting a project in another browser window. Is it normally?

**Comment by alansemenov** [comment] 2020-05-11 12:07
There should be no messages in **another** window, no. But there should be a message in the same window where the project was deleted.

**Comment by sgauruseu** [comment] 2020-05-11 12:12
So we have correct behavior now - message appears only window where project was deleted.
This bug is fixed now.

**Comment by ashklianko** [comment] 2020-05-11 13:42
Can be closed?

**Closed** 2020-05-12 08:06 UTC
Labels: Bug, Not in Changelog
