### ISSUE TITLE
Content editor menu overlay not displayed properly

### ISSUE THREAD

**Issue by vot-enonic** [enonic/app-contentstudio#2872] opened 2021-02-15 10:52 UTC
The default width of the content editor field breaks the title and pushes concurrent menu elements too far down, which can interfere with the editing process (and this is very annoying!). In the example GIF below, "Settings" get in the way of the "Heading" dropdown menu.
![content editor overlay](https://user-images.githubusercontent.com/43465080/107937450-375add00-6f84-11eb-84f6-fb3246fdd780.gif)

**Comment by alansemenov** [comment] 2021-02-15 12:44
Duplicate of https://github.com/enonic/lib-admin-ui/issues/1793. Will be fixed in CS 3.2.1

**Closed as completed by alansemenov** 2021-02-15 12:44 UTC
