### ISSUE TITLE
Permissions updated version item appears only for published content in Archive

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#5402] opened 2022-11-08 09:40 UTC
1. Archive a published-folder, go to Archive and open Versions widget 

`Permissions updated` item is present in the widget 

![image](https://user-images.githubusercontent.com/3728712/200527894-9bdc8eb3-2bc9-4578-9859-6fb8f7ff2067.png)

2. Archive a new-folder, go to Archive and open Versions widget 
`Permissions updated` item is not  present in the widget:
 
![image](https://user-images.githubusercontent.com/3728712/200528273-740b417d-da73-48b2-b930-f5dc977979ff.png)

But actually both folders have changes in permissions, because `Inherit permissions` checkboxes were automatically unchecked when both content were archived

And permissions updated item is not displayed after restoring the published content

![image](https://user-images.githubusercontent.com/3728712/200529825-bf024a36-5008-4c34-8454-a082ab22f7d8.png)

**Comment by sgauruseu** [comment] 2022-12-30 10:07
I can not reproduce this issue in new builds

**Comment by ashklianko** [comment] 2022-12-30 10:08
Couldn't reproduce it also, closing

**Closed as completed by ashklianko** 2022-12-30 10:08 UTC
Labels: Bug, Can't Reproduce
