### ISSUE TITLE
Keep parent item expanded after adding or deleting a child item 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#87] opened 2019-01-21 13:30 UTC
1. Type a name of existing site in filter -input  and select the site .
2. Expand the site 

![image](https://user-images.githubusercontent.com/3728712/51477504-becfc500-1d99-11e9-9b83-8bd2f8a975d7.png)

3. Click on New button and open new folder-wizard
4. type a name and close the folder-wizard

BUG: 
Expected - site should be expanded after the adding
Actual the site is collapsed

**Comment by alansemenov** [comment] 2019-11-12 10:23
Duplicate of https://github.com/enonic/app-contentstudio/issues/1173

**Closed by alansemenov** 2019-11-12 10:23 UTC
Labels: Improvement
