### ISSUE TITLE
Tooltip for workflow state should not be shown for invalid content

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#3708] opened 2021-10-20 10:47 UTC
1. Create a ready for publishing shortcut, for example
2. Click on remove icon and remove the selected target option in the shortcut
3. Go to grid, move the cursor to the shortcut

**BUG**:  `Ready for publishing` tooltip appears

![image](https://user-images.githubusercontent.com/3728712/138079316-4d92bfdb-62bf-4c97-aa18-0708eec12827.png)
 
**Expected** - the tooltip should be hidden for invalid content

**Comment by alansemenov** [comment] 2021-11-24 20:38
See also https://github.com/enonic/app-contentstudio/issues/3143

**Comment by alansemenov** [comment] 2022-04-08 12:33
Duplicate of https://github.com/enonic/app-contentstudio/issues/3143

**Closed as completed by alansemenov** 2022-04-08 12:33 UTC
Labels: Bug
