### ISSUE TITLE
Context Panel: switch between docked and floating mode 

### ISSUE THREAD

**Issue by ashklianko** [enonic/app-contentstudio#3849] opened 2021-11-17 15:43 UTC
Currently docked mode in wizard panel working only when live edit panel is open (in that case it shares space with it in split panel). 

To fo:
1. If live edit is open and has enough space - show live and docked together
2. If docked panel to be shown and live edit is closed - open live edit and give all available space to the docked panel 
3. If live edit is to be closed and docked panel is open - just give all live panel's spave to docked panel

So in general need to distribute live panel's space to docked panel when live panel is not supposed to be visible 

To refactor if possible:
1. Remove NonMobileContextPanelsManager and move required logic to ContextSplitPanel
2. Remove ActiveContextPanelManager
3. Remove floating panel in ContextSplitPanel
4. Docked panel to be used in floating mode via css

**Comment by alansemenov** [comment] 2021-11-18 14:57
Duplicate of https://github.com/enonic/app-contentstudio/issues/3850

**Closed as completed by alansemenov** 2021-11-18 14:57 UTC
Labels: Bug, Won't Fix, Tech Debt
