### ISSUE TITLE
Incorrect height of toolbar in the Image Editor

### ISSUE THREAD

**Issue by jsi** [enonic/app-contentstudio#35] opened 2019-01-11 10:19 UTC
@alansemenov commented on [Thu Dec 06 2018](https://github.com/enonic/app-contentstudio-old/issues/597)

![image](https://user-images.githubusercontent.com/11612490/49584443-aa577a80-f95b-11e8-8930-96d6c87ad686.png)

![image](https://user-images.githubusercontent.com/11612490/49584416-957ae700-f95b-11e8-9fbe-6675ba21ed2d.png)

**Comment by alansemenov** [comment] 2019-01-28 09:12
Duplicate of https://github.com/enonic/app-contentstudio/issues/38

**Closed by alansemenov** 2019-01-28 09:12 UTC
Labels: Bug
