### ISSUE TITLE
Content Wizard - broken layout in nested content  with long names

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2854] opened 2021-02-08 10:24 UTC
1. Create  a several nested folders  with long names.
  
![image](https://user-images.githubusercontent.com/3728712/107205482-fa846880-6a0e-11eb-8acf-6f1e626d429f.png)

2. Open child folders in wizard : 

There is enough space for the path in the first line, but a part of the path is moved to the second line.

![image](https://user-images.githubusercontent.com/3728712/107206310-e725cd00-6a0f-11eb-9406-de9a51782d91.png)

![image](https://user-images.githubusercontent.com/3728712/107207018-d75ab880-6a10-11eb-9582-ff5485c40c33.png)

**Comment by alansemenov** [comment] 2021-02-16 10:43
Duplicate of https://github.com/enonic/app-contentstudio/issues/1499

**Closed by alansemenov** 2021-02-16 10:43 UTC
Labels: Bug
