### ISSUE TITLE
Versions Widget - version items are not correctly shown 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#5555] opened 2022-12-08 15:45 UTC
1. Open wizard for new folder, fill in the name input, save it 
2. Publish the folder  in the wizard

**BUG**  - Issue 1: Published item is not displayed in the widget 

![image](https://user-images.githubusercontent.com/3728712/206491614-6a2d3e36-c884-46eb-8e7e-e3fc083cc433.png)

**BUG** - Issue 2:  Incorrect status is displayed after a content scheduled for publishing,  
                Expected status is 'Publishing Scheduled', but actual is 'Published'

**Comment by alansemenov** [comment] 2022-12-12 09:18
Caused by and fixed in https://github.com/enonic/xp/issues/9926

**Closed as completed by alansemenov** 2022-12-12 09:18 UTC
Labels: Bug, Not in Changelog, Test is Failing
