### ISSUE TITLE
Issues on hazelcast.enonic.cloud  

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1613] opened 2020-03-16 08:00 UTC
**Case 1**. Endless spinner and error in console after scrolling browse panel (about 1000 items in grid)
  - open Filter Panel , click on Images checkbox - **503 error appears in console**
  

![image](https://user-images.githubusercontent.com/3728712/76734916-f99e7480-6774-11ea-8ffc-eb078400ec32.png)
 
- try to scroll  browse panel:  Endless spinner + errors in console: 

![image](https://user-images.githubusercontent.com/3728712/76735066-379b9880-6775-11ea-9e45-3e1d0bd066e1.png)

**Case 2:**   Duplicate, Publish, Delete  actions take a very long time

![image](https://user-images.githubusercontent.com/3728712/76735379-d4f6cc80-6775-11ea-87d8-fd5f4fc15714.png)

**Case 3 :  Errors after installing Features :** 

![image](https://user-images.githubusercontent.com/3728712/76735459-0374a780-6776-11ea-9235-87a19aea350d.png)

**Comment by rymsha** [comment] 2020-05-26 16:46
This is a duplicate of enonic/xp#8064

**Closed by rymsha** 2020-05-26 16:46 UTC
Labels: Bug
