### ISSUE TITLE
Attachment remains in Attachments Widget after removing it in wizard

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#307] opened 2019-03-14 10:50 UTC
1. Open new attachment wizard, type a name and upload a file
2. The content is saved automatically(OK). Remove the attached file in wizard.

**Bug:  removed file remains in  Attachments Widget**

![image](https://user-images.githubusercontent.com/3728712/54351105-d1f76680-465f-11e9-961a-c98bb4d060d9.png)

**Comment by alansemenov** [comment] 2019-03-14 10:59
Duplicate of https://github.com/enonic/xp/issues/7000

**Closed by alansemenov** 2019-03-14 10:59 UTC
Labels: Bug
