### ISSUE TITLE
Document Content Projects Lib

### ISSUE THREAD

**Issue by jsi** [enonic/app-contentstudio#1807] opened 2020-05-11 13:22 UTC
Set Done in TRR minutes when ready: https://enonic.atlassian.net/wiki/spaces/TQ/pages/491061253/TRR+XP+v7.3.0+CS+v3.0.0+2020-05-07

**Comment by alansemenov** [comment] 2020-05-14 14:08
Duplicate of https://github.com/enonic/doc-xp/issues/130

**Closed by alansemenov** 2020-05-14 14:08 UTC
Labels: Documentation, Not in Changelog
