### ISSUE TITLE
Inspect panel - issues after applying changes

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#6756] opened 2023-08-31 13:16 UTC
**Case 1**
1. Open `Features`, insert `Cities List`
2. Update the tile in the Inspect Panel
3. Click on `Apply` button
4. Click on `default` item in PCV

BUG - Inspect Panel is not updated after selecting another item in PCV 

![image](https://github.com/enonic/app-contentstudio/assets/3728712/cc1f6656-0af7-4079-b7e5-2a8061d26f51)

**Comment by alansemenov** [comment] 2023-08-31 13:18
This is duplicate of https://github.com/enonic/app-contentstudio/issues/6754

**Closed as completed by alansemenov** 2023-08-31 13:18 UTC
Labels: Bug, Duplicate, Not in Changelog
