### ISSUE TITLE
Fragment wizard - required Tab-Bar should be activated in Context Window

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#617] opened 2019-07-08 10:40 UTC
1. Open a site and insert Text Component(type a text, insert image...)
2. Select the component in Page Component View and click on `Save as Fragment`
3. switch to Fragment Wizard

Issue: Text bar item should be opened in Context Window
Actual: Insert tab is opened 

![image](https://user-images.githubusercontent.com/3728712/60804219-ab68b880-a185-11e9-96b9-07ba09f0c013.png)

**Expected:**

![image](https://user-images.githubusercontent.com/3728712/60804347-fedb0680-a185-11e9-8b0f-d553a429f7b5.png)

**Comment by alansemenov** [comment] 2020-05-28 12:32
@ashklianko check if this is still actual

**Comment by ashklianko** [comment] 2020-05-28 13:32
Not a bug, mentioned context window tab will be open after item selection. 
Possible improvement to implement: since it is fragment wizard and it's page has only one item we actually don't need Insert tab and might show just one tab in context window with component info, no matter if it is selected or not.
Closing for now

**Closed by ashklianko** 2020-05-28 13:32 UTC
Labels: Bug
