### ISSUE TITLE
Layer Widget: Make the next layer visible in the context panel

### ISSUE THREAD

**Issue by vot-enonic** [enonic/app-contentstudio#7892] opened 2024-09-24 13:48 UTC
It's annoying that I have to click "Show all" to see the layer below the content item I'm currently in.
![image](https://github.com/user-attachments/assets/6f50c06e-fdd7-4643-9a4e-6d5f2c8b803a)

![image](https://github.com/user-attachments/assets/c8552d22-69ab-47b5-a914-73bbd8a0085e)

If it's just one layer below, it should be visible in the panel. If it's like five layers below, I understand that you have to click to see all the items superimposed.

**Comment by alansemenov** [comment] 2024-11-05 08:36
Duplicate of https://github.com/enonic/app-contentstudio-plus/issues/1409

**Closed as not planned by alansemenov** 2024-11-05 08:36 UTC
Labels: Duplicate, Feature, Won't Fix
