### ISSUE TITLE
Insert Image dialog - upload button is not displayed in the dialog

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#5002] opened 2022-08-19 09:46 UTC
This issue is reproducing in 4.2 

1. Open a site , insert text component 
2. Click on Insert Image button 

**Bug**: Upload image is not displayed in the dialog 

![image](https://user-images.githubusercontent.com/3728712/185592461-0b327d0c-a1f8-4321-af1d-e67da67a964a.png)

3. Select an image, then click on remove icon 

![image](https://user-images.githubusercontent.com/3728712/185592188-7a1e58b2-f587-494c-ba31-d560cadd9818.png)

Upload button gets visible after clcicking on Remove button

**Comment by ashklianko** [comment] 2022-08-21 20:22
Seems to be an issue only in 4.2 branch (fixed by [this commit](https://github.com/enonic/app-contentstudio/commit/241c3de1507d560b2c717ed16db581436f57e79f) )

@sgauruseu please check if this is reproduced in master, otherwise should be closed

**Closed as completed** 2022-08-22 07:59 UTC
Labels: Bug
