### ISSUE TITLE
Editor - Insert image dialog does not show the whole image selector dropdown

### ISSUE THREAD

**Issue by sigdestad** [enonic/app-contentstudio#842] opened 2019-08-27 11:53 UTC
Here is a screenshot:
![Screenshot 2019-08-27 at 13 51 50](https://user-images.githubusercontent.com/482228/63768987-f1164780-c8d1-11e9-80fc-d9eab460e0a9.png)

This is a blocker for our demo, and the 2.1 release of content studio

**Comment by sgauruseu** [comment] 2019-08-28 11:21
I reproduced it  in FF and MS Edge browsers, there are no problems in Chrome browser.

Edge: 
![image](https://user-images.githubusercontent.com/3728712/63851545-11f89e80-c99f-11e9-809d-67b48b21cce6.png)

**Comment by edloidas** [comment] 2019-08-28 11:28
The problem is related to another [issue](https://github.com/enonic/app-contentstudio/issues/823) (_also in [lib-admin-ui](https://github.com/enonic/lib-admin-ui/issues/1078)_) that is not yet merged. The fix should resolve both issues.

**Comment by edloidas** [comment] 2019-08-29 09:11
Fixed in the recent [PR](https://github.com/enonic/lib-admin-ui/pull/1080) in `lib-admin-ui`.

**Closed** 2019-09-03 12:10 UTC
Labels: Bug, Duplicate, Not in Changelog
